# Generated by Django 5.2 on 2025-12-30 18:02

import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Instrument Group",
                "verbose_name_plural": "Instrument Groups",
                "indexes": [
                    models.Index(fields=["name"], name="reference_d_name_aacdb9_idx")
                ],
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="InstrumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The group to which this type belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="reference_data.instrumentgroup",
                        verbose_name="Instrument Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument Type",
                "verbose_name_plural": "Instrument Types",
            },
        ),
        migrations.CreateModel(
            name="Issuer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Short Name"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "issuer_group",
                    models.CharField(
                        blank=True,
                        help_text="Group classification (e.g., 'Sovereign', 'Corporate')",
                        max_length=255,
                        null=True,
                        verbose_name="Issuer Group",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issuer",
                "verbose_name_plural": "Issuers",
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isin",
                    models.CharField(
                        blank=True,
                        help_text="International Securities Identification Number.",
                        max_length=255,
                        null=True,
                        verbose_name="ISIN",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        blank=True,
                        help_text="Trading ticker symbol.",
                        max_length=255,
                        null=True,
                        verbose_name="Ticker",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name or description of the instrument.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "currency",
                    djmoney.models.fields.CurrencyField(default="XAF", max_length=3),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        help_text="Economic sector classification.",
                        max_length=255,
                        null=True,
                        verbose_name="Sector",
                    ),
                ),
                (
                    "maturity_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Maturity Date"
                    ),
                ),
                (
                    "coupon_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coupon rate for bonds (as percentage).",
                        max_digits=10,
                        null=True,
                        verbose_name="Coupon Rate",
                    ),
                ),
                (
                    "valuation_method",
                    models.CharField(
                        choices=[
                            ("mark_to_market", "Mark to Market"),
                            ("mark_to_model", "Mark to Model"),
                            ("external_appraisal", "External Appraisal"),
                            ("manual_declared", "Manual Declared"),
                        ],
                        default="mark_to_market",
                        help_text="How this instrument is valued.",
                        max_length=255,
                        verbose_name="Valuation Method",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "instrument_group",
                    models.ForeignKey(
                        help_text="The group to which this instrument belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="reference_data.instrumentgroup",
                        verbose_name="Instrument Group",
                    ),
                ),
                (
                    "instrument_type",
                    models.ForeignKey(
                        help_text="The type of this instrument.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="reference_data.instrumenttype",
                        verbose_name="Instrument Type",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        help_text="The issuer of this instrument.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="reference_data.issuer",
                        verbose_name="Issuer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument",
                "verbose_name_plural": "Instruments",
            },
        ),
        migrations.CreateModel(
            name="IssuerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        choices=[
                            ("S&P", "Standard & Poor's"),
                            ("Moody's", "Moody's"),
                            ("Fitch", "Fitch"),
                            ("Bloomfield", "Bloomfield"),
                        ],
                        help_text="Agency that assigned the rating (e.g., 'S&P', 'Moody's', 'Fitch').",
                        max_length=255,
                        verbose_name="Rating Agency",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        help_text="Credit rating assigned (e.g., 'AAA', 'BB+').",
                        max_length=255,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "date_assigned",
                    models.DateField(
                        help_text="Date this rating became effective.",
                        verbose_name="Date Assigned",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rating is currently the active rating from this agency.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        help_text="The issuer to which this rating applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="reference_data.issuer",
                        verbose_name="Issuer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issuer Rating",
                "verbose_name_plural": "Issuer Ratings",
                "ordering": ["-date_assigned", "agency"],
            },
        ),
        migrations.AddIndex(
            model_name="instrumenttype",
            index=models.Index(
                fields=["group", "name"], name="reference_d_group_i_9df441_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="instrumenttype",
            unique_together={("group", "name")},
        ),
        migrations.AddIndex(
            model_name="issuer",
            index=models.Index(
                fields=["organization", "name"], name="reference_d_organiz_3c9f67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuer",
            index=models.Index(
                fields=["organization", "country"],
                name="reference_d_organiz_92cdb6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuer",
            index=models.Index(
                fields=["organization", "issuer_group"],
                name="reference_d_organiz_a7c80a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuer",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "isin"], name="reference_d_organiz_d86703_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "ticker"], name="reference_d_organiz_cf4dca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "instrument_group"],
                name="reference_d_organiz_c55099_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "instrument_type"],
                name="reference_d_organiz_93dc49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "currency"],
                name="reference_d_organiz_aa88a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "issuer"], name="reference_d_organiz_65b6dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "country"],
                name="reference_d_organiz_914605_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuerrating",
            index=models.Index(
                fields=["issuer", "agency"], name="reference_d_issuer__4d91c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuerrating",
            index=models.Index(
                fields=["issuer", "date_assigned"],
                name="reference_d_issuer__3b1e42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuerrating",
            index=models.Index(
                fields=["agency", "is_active"], name="reference_d_agency_6b28da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuerrating",
            unique_together={("issuer", "agency", "date_assigned")},
        ),
    ]
