# Generated by Django 5.2 on 2025-12-30 21:02

import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketDataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the source (e.g., 'BVMAC', 'BEAC', 'BLOOMBERG')",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the source",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Priority rank (lower = higher priority, e.g., 1 = best, 10 = worst)",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exchange", "Exchange"),
                            ("central_bank", "Central Bank"),
                            ("vendor", "Vendor"),
                            ("manual", "Manual"),
                            ("custodian", "Custodian"),
                        ],
                        help_text="Type of source (EXCHANGE, CENTRAL_BANK, VENDOR, MANUAL, CUSTODIAN)",
                        max_length=20,
                        null=True,
                        verbose_name="Source Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Market Data Source",
                "verbose_name_plural": "Market Data Sources",
                "ordering": ["priority", "code"],
                "indexes": [
                    models.Index(fields=["code"], name="reference_d_code_4baa78_idx"),
                    models.Index(
                        fields=["priority", "is_active"],
                        name="reference_d_priorit_b596db_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InstrumentPriceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for which this price is valid",
                        verbose_name="Date",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("close", "Close"),
                            ("bid", "Bid"),
                            ("ask", "Ask"),
                            ("mid", "Mid"),
                            ("open", "Open"),
                            ("high", "High"),
                            ("low", "Low"),
                            ("nav", "NAV"),
                        ],
                        default="close",
                        help_text="Type of price (close, bid, ask, etc.)",
                        max_length=10,
                        verbose_name="Price Type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Market price per unit (interpretation depends on quote_convention)",
                        max_digits=20,
                        verbose_name="Price",
                    ),
                ),
                (
                    "quote_convention",
                    models.CharField(
                        choices=[
                            ("price", "Price"),
                            ("percent_of_par", "Percent of Par"),
                            ("yield", "Yield"),
                        ],
                        default="price",
                        help_text="How to interpret the price (PRICE, PERCENT_OF_PAR, YIELD)",
                        max_length=20,
                        verbose_name="Quote Convention",
                    ),
                ),
                (
                    "clean_or_dirty",
                    models.CharField(
                        choices=[("clean", "Clean"), ("dirty", "Dirty"), ("na", "N/A")],
                        default="na",
                        help_text="Whether price includes accrued interest (CLEAN, DIRTY, NA)",
                        max_length=10,
                        verbose_name="Clean or Dirty",
                    ),
                ),
                (
                    "revision",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Revision number (0 = initial, 1+ = corrections)",
                        verbose_name="Revision",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trading volume for the date",
                        max_digits=20,
                        null=True,
                        verbose_name="Volume",
                    ),
                ),
                (
                    "currency",
                    djmoney.models.fields.CurrencyField(
                        blank=True,
                        default="XAF",
                        help_text="Currency override if different from instrument currency (rare)",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        help_text="When this observation was received/recorded",
                        verbose_name="Observed At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_observations",
                        to="reference_data.instrument",
                        verbose_name="Instrument",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_data_observations",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument Price Observation",
                "verbose_name_plural": "Instrument Price Observations",
                "ordering": ["-date", "instrument", "-observed_at"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for which this price is valid",
                        verbose_name="Date",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("close", "Close"),
                            ("bid", "Bid"),
                            ("ask", "Ask"),
                            ("mid", "Mid"),
                            ("open", "Open"),
                            ("high", "High"),
                            ("low", "Low"),
                            ("nav", "NAV"),
                        ],
                        default="close",
                        help_text="Type of price (close, bid, ask, etc.)",
                        max_length=10,
                        verbose_name="Price Type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Market price per unit (stored directly for performance)",
                        max_digits=20,
                        verbose_name="Price",
                    ),
                ),
                (
                    "quote_convention",
                    models.CharField(
                        choices=[
                            ("price", "Price"),
                            ("percent_of_par", "Percent of Par"),
                            ("yield", "Yield"),
                        ],
                        default="price",
                        help_text="How to interpret the price (PRICE, PERCENT_OF_PAR, YIELD)",
                        max_length=20,
                        verbose_name="Quote Convention",
                    ),
                ),
                (
                    "clean_or_dirty",
                    models.CharField(
                        choices=[("clean", "Clean"), ("dirty", "Dirty"), ("na", "N/A")],
                        default="na",
                        help_text="Whether price includes accrued interest (CLEAN, DIRTY, NA)",
                        max_length=10,
                        verbose_name="Clean or Dirty",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trading volume for the date",
                        max_digits=20,
                        null=True,
                        verbose_name="Volume",
                    ),
                ),
                (
                    "currency",
                    djmoney.models.fields.CurrencyField(
                        blank=True,
                        default="XAF",
                        help_text="Currency override if different from instrument currency (rare)",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "selection_reason",
                    models.CharField(
                        choices=[
                            ("auto_policy", "Auto Policy"),
                            ("manual_override", "Manual Override"),
                            ("only_available", "Only Available"),
                        ],
                        default="auto_policy",
                        help_text="Why this price was selected (AUTO_POLICY, MANUAL_OVERRIDE, etc.)",
                        max_length=20,
                        verbose_name="Selection Reason",
                    ),
                ),
                (
                    "selected_at",
                    models.DateTimeField(
                        help_text="When this price was selected/canonicalized",
                        verbose_name="Selected At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_prices",
                        to="reference_data.instrument",
                        verbose_name="Instrument",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who manually selected this price (if manual override)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_prices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Selected By",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The observation that was selected (optional, for audit trail)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canonical_prices",
                        to="reference_data.instrumentpriceobservation",
                        verbose_name="Observation",
                    ),
                ),
                (
                    "chosen_source",
                    models.ForeignKey(
                        help_text="The source that was selected for this canonical price",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canonical_market_data",
                        to="reference_data.marketdatasource",
                        verbose_name="Chosen Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument Price",
                "verbose_name_plural": "Instrument Prices",
                "ordering": ["-date", "instrument"],
            },
        ),
        migrations.CreateModel(
            name="FXRateObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        help_text="Base currency code (e.g., 'XAF')",
                        max_length=3,
                        verbose_name="Base Currency",
                    ),
                ),
                (
                    "quote_currency",
                    models.CharField(
                        help_text="Quote currency code (e.g., 'USD')",
                        max_length=3,
                        verbose_name="Quote Currency",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Exchange rate (1 base = rate quote)",
                        max_digits=20,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("mid", "Mid"),
                            ("official", "Official"),
                            ("fixing", "Fixing"),
                        ],
                        default="mid",
                        help_text="Type of FX rate (MID, OFFICIAL, FIXING)",
                        max_length=20,
                        verbose_name="Rate Type",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for which this rate is valid",
                        verbose_name="Date",
                    ),
                ),
                (
                    "revision",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Revision number (0 = initial, 1+ = corrections)",
                        verbose_name="Revision",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        help_text="When this observation was received/recorded",
                        verbose_name="Observed At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fx_rate_observations",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "FX Rate Observation",
                "verbose_name_plural": "FX Rate Observations",
                "ordering": [
                    "-date",
                    "base_currency",
                    "quote_currency",
                    "-observed_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="FXRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        help_text="Base currency code (e.g., 'XAF')",
                        max_length=3,
                        verbose_name="Base Currency",
                    ),
                ),
                (
                    "quote_currency",
                    models.CharField(
                        help_text="Quote currency code (e.g., 'USD')",
                        max_length=3,
                        verbose_name="Quote Currency",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Exchange rate (1 base = rate quote)",
                        max_digits=20,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("mid", "Mid"),
                            ("official", "Official"),
                            ("fixing", "Fixing"),
                        ],
                        default="mid",
                        help_text="Type of FX rate (MID, OFFICIAL, FIXING)",
                        max_length=20,
                        verbose_name="Rate Type",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for which this rate is valid",
                        verbose_name="Date",
                    ),
                ),
                (
                    "selection_reason",
                    models.CharField(
                        choices=[
                            ("auto_policy", "Auto Policy"),
                            ("manual_override", "Manual Override"),
                            ("only_available", "Only Available"),
                        ],
                        default="auto_policy",
                        help_text="Why this rate was selected (AUTO_POLICY, MANUAL_OVERRIDE, etc.)",
                        max_length=20,
                        verbose_name="Selection Reason",
                    ),
                ),
                (
                    "selected_at",
                    models.DateTimeField(
                        help_text="When this rate was selected/canonicalized",
                        verbose_name="Selected At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who manually selected this rate (if manual override)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_fx_rates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Selected By",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The observation that was selected (optional, for audit trail)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canonical_fx_rates",
                        to="reference_data.fxrateobservation",
                        verbose_name="Observation",
                    ),
                ),
                (
                    "chosen_source",
                    models.ForeignKey(
                        help_text="The source that was selected for this canonical rate",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canonical_fx_rates",
                        to="reference_data.marketdatasource",
                        verbose_name="Chosen Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "FX Rate",
                "verbose_name_plural": "FX Rates",
                "ordering": ["-date", "base_currency", "quote_currency"],
            },
        ),
        migrations.CreateModel(
            name="YieldCurve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the yield curve (e.g., 'XAF Government Curve')",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "curve_type",
                    models.CharField(
                        choices=[
                            ("govt", "Government"),
                            ("swap", "Swap"),
                            ("ois", "OIS"),
                            ("corporate", "Corporate"),
                            ("policy", "Policy Rate"),
                        ],
                        help_text="Type of curve (GOVT, SWAP, OIS, CORPORATE, POLICY)",
                        max_length=20,
                        verbose_name="Curve Type",
                    ),
                ),
                (
                    "currency",
                    djmoney.models.fields.CurrencyField(
                        default="XAF",
                        help_text="Currency code for this curve",
                        max_length=3,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        help_text="Country for this curve",
                        max_length=2,
                        verbose_name="Country",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Yield Curve",
                "verbose_name_plural": "Yield Curves",
                "indexes": [
                    models.Index(
                        fields=["currency", "curve_type"],
                        name="reference_d_currenc_6e5e69_idx",
                    ),
                    models.Index(
                        fields=["currency"], name="reference_d_currenc_d171a9_idx"
                    ),
                    models.Index(
                        fields=["curve_type"], name="reference_d_curve_t_7ea953_idx"
                    ),
                ],
                "unique_together": {("currency", "name")},
            },
        ),
        migrations.CreateModel(
            name="YieldCurvePointObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenor",
                    models.CharField(
                        help_text="Tenor description for display (e.g., '1M', '3M', '1Y', '5Y', '10Y')",
                        max_length=10,
                        verbose_name="Tenor",
                    ),
                ),
                (
                    "tenor_days",
                    models.IntegerField(
                        help_text="Tenor in days (e.g., 30 for 1M, 365 for 1Y, 1825 for 5Y) - REQUIRED",
                        verbose_name="Tenor Days",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Interest rate as percentage (e.g., 5.50 for 5.5%)",
                        max_digits=8,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for which this yield point is valid",
                        verbose_name="Date",
                    ),
                ),
                (
                    "revision",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Revision number (0 = initial, 1+ = corrections)",
                        verbose_name="Revision",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        help_text="When this observation was received/recorded",
                        verbose_name="Observed At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "curve",
                    models.ForeignKey(
                        help_text="The yield curve this observation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_observations",
                        to="reference_data.yieldcurve",
                        verbose_name="Curve",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yield_curve_observations",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yield Curve Point Observation",
                "verbose_name_plural": "Yield Curve Point Observations",
                "ordering": ["-date", "curve", "tenor_days", "-observed_at"],
            },
        ),
        migrations.CreateModel(
            name="YieldCurvePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenor",
                    models.CharField(
                        help_text="Tenor description for display (e.g., '1M', '3M', '1Y', '5Y', '10Y')",
                        max_length=10,
                        verbose_name="Tenor",
                    ),
                ),
                (
                    "tenor_days",
                    models.IntegerField(
                        help_text="Tenor in days (e.g., 30 for 1M, 365 for 1Y, 1825 for 5Y) - REQUIRED",
                        verbose_name="Tenor Days",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Interest rate as percentage (e.g., 5.50 for 5.5%)",
                        max_digits=8,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for which this yield point is valid",
                        verbose_name="Date",
                    ),
                ),
                (
                    "selection_reason",
                    models.CharField(
                        choices=[
                            ("auto_policy", "Auto Policy"),
                            ("manual_override", "Manual Override"),
                            ("only_available", "Only Available"),
                        ],
                        default="auto_policy",
                        help_text="Why this point was selected (AUTO_POLICY, MANUAL_OVERRIDE, etc.)",
                        max_length=20,
                        verbose_name="Selection Reason",
                    ),
                ),
                (
                    "selected_at",
                    models.DateTimeField(
                        help_text="When this point was selected/canonicalized",
                        verbose_name="Selected At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "chosen_source",
                    models.ForeignKey(
                        help_text="The source that was selected for this canonical point",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canonical_yield_curve_points",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
                (
                    "curve",
                    models.ForeignKey(
                        help_text="The yield curve this point belongs to (REQUIRED)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="reference_data.yieldcurve",
                        verbose_name="Curve",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who manually selected this point (if manual override)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_yield_curve_points",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Selected By",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The observation that was selected (optional, for audit trail)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canonical_points",
                        to="reference_data.yieldcurvepointobservation",
                        verbose_name="Observation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yield Curve Point",
                "verbose_name_plural": "Yield Curve Points",
                "ordering": ["-date", "curve", "tenor_days"],
            },
        ),
        migrations.AddIndex(
            model_name="instrumentpriceobservation",
            index=models.Index(
                fields=["instrument", "date", "price_type"],
                name="reference_d_instrum_aeb0f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrumentpriceobservation",
            index=models.Index(fields=["date"], name="reference_d_date_455550_idx"),
        ),
        migrations.AddIndex(
            model_name="instrumentpriceobservation",
            index=models.Index(
                fields=["source", "date"], name="reference_d_source__118277_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrumentpriceobservation",
            index=models.Index(
                fields=["observed_at"], name="reference_d_observe_df54ae_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="instrumentpriceobservation",
            unique_together={
                ("instrument", "date", "price_type", "source", "revision")
            },
        ),
        migrations.AddIndex(
            model_name="instrumentprice",
            index=models.Index(
                fields=["instrument", "date"], name="reference_d_instrum_d9a8d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrumentprice",
            index=models.Index(fields=["date"], name="reference_d_date_80c4a5_idx"),
        ),
        migrations.AddIndex(
            model_name="instrumentprice",
            index=models.Index(
                fields=["instrument", "date", "price_type"],
                name="reference_d_instrum_3b8d2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrumentprice",
            index=models.Index(
                fields=["chosen_source"], name="reference_d_chosen__25c426_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="instrumentprice",
            unique_together={("instrument", "date", "price_type")},
        ),
        migrations.AddIndex(
            model_name="fxrateobservation",
            index=models.Index(
                fields=["base_currency", "quote_currency", "date"],
                name="reference_d_base_cu_e113a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fxrateobservation",
            index=models.Index(fields=["date"], name="reference_d_date_ac7459_idx"),
        ),
        migrations.AddIndex(
            model_name="fxrateobservation",
            index=models.Index(
                fields=["source", "date"], name="reference_d_source__2f8e16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fxrateobservation",
            index=models.Index(
                fields=["observed_at"], name="reference_d_observe_30ec93_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fxrateobservation",
            unique_together={
                (
                    "base_currency",
                    "quote_currency",
                    "date",
                    "rate_type",
                    "source",
                    "revision",
                )
            },
        ),
        migrations.AddIndex(
            model_name="fxrate",
            index=models.Index(
                fields=["base_currency", "quote_currency", "date"],
                name="reference_d_base_cu_eb9aeb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fxrate",
            index=models.Index(fields=["date"], name="reference_d_date_96578f_idx"),
        ),
        migrations.AddIndex(
            model_name="fxrate",
            index=models.Index(
                fields=["base_currency"], name="reference_d_base_cu_ed0c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fxrate",
            index=models.Index(
                fields=["quote_currency"], name="reference_d_quote_c_d15ec1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fxrate",
            index=models.Index(
                fields=["rate_type"], name="reference_d_rate_ty_10ca71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fxrate",
            index=models.Index(
                fields=["chosen_source"], name="reference_d_chosen__a96dd4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fxrate",
            constraint=models.UniqueConstraint(
                fields=("base_currency", "quote_currency", "date", "rate_type"),
                name="uniq_fx_rate_currency_pair_date_type",
            ),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepointobservation",
            index=models.Index(
                fields=["curve", "tenor_days", "date"],
                name="reference_d_curve_i_91d226_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepointobservation",
            index=models.Index(
                fields=["curve", "date"], name="reference_d_curve_i_02adc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepointobservation",
            index=models.Index(fields=["date"], name="reference_d_date_9b0535_idx"),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepointobservation",
            index=models.Index(
                fields=["source", "date"], name="reference_d_source__ef3103_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepointobservation",
            index=models.Index(
                fields=["observed_at"], name="reference_d_observe_d13a12_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="yieldcurvepointobservation",
            unique_together={("curve", "tenor_days", "date", "source", "revision")},
        ),
        migrations.AddIndex(
            model_name="yieldcurvepoint",
            index=models.Index(
                fields=["curve", "tenor_days", "date"],
                name="reference_d_curve_i_86655c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepoint",
            index=models.Index(
                fields=["curve", "date"], name="reference_d_curve_i_df5ba7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepoint",
            index=models.Index(fields=["date"], name="reference_d_date_508a45_idx"),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepoint",
            index=models.Index(
                fields=["chosen_source"], name="reference_d_chosen__2b5579_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="yieldcurvepoint",
            constraint=models.UniqueConstraint(
                fields=("curve", "tenor_days", "date"),
                name="uniq_curve_tenor_days_date",
            ),
        ),
    ]
