# Generated by Django 5.2 on 2025-12-30 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0002_marketdatasource_instrumentpriceobservation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YieldCurveImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded Excel file with yield curve data.",
                        upload_to="market_data/yield_curves/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True,
                        help_text="Sheet name if file has multiple sheets (e.g., 'CM', 'GA', 'CG').",
                        max_length=255,
                        null=True,
                        verbose_name="Sheet Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("validating", "Validating"),
                            ("processing", "Processing"),
                            ("importing", "Importing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        help_text="Current import status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if import failed.",
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "observations_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of observations created.",
                        verbose_name="Observations Created",
                    ),
                ),
                (
                    "observations_updated",
                    models.IntegerField(
                        default=0,
                        help_text="Number of observations updated.",
                        verbose_name="Observations Updated",
                    ),
                ),
                (
                    "canonical_points_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of canonical points created (if canonicalized).",
                        verbose_name="Canonical Points Created",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the import completed.",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this import.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yield_curve_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "curve",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific curve to import (if None, imports all curves in file).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imports",
                        to="reference_data.yieldcurve",
                        verbose_name="Curve",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Market data source (e.g., BEAC).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yield_curve_imports",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yield Curve Import",
                "verbose_name_plural": "Yield Curve Imports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "status"],
                        name="reference_d_source__b91af2_idx",
                    ),
                    models.Index(
                        fields=["curve", "status"],
                        name="reference_d_curve_i_c7f6cc_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="reference_d_created_e9e16c_idx"
                    ),
                ],
            },
        ),
    ]
