# Generated by Django 5.2 on 2025-12-31 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0003_yieldcurveimport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fxrateobservation",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("buy", "Buy"),
                    ("sell", "Sell"),
                    ("mid", "Mid"),
                    ("official", "Official"),
                    ("fixing", "Fixing"),
                ],
                default="mid",
                help_text="Type of FX rate (MID, OFFICIAL, FIXING)",
                max_length=20,
                verbose_name="Rate Type",
            ),
        ),
        migrations.CreateModel(
            name="FXRateImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded Excel file with FX rate data.",
                        upload_to="market_data/fx_rates/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True,
                        help_text="Sheet name if file has multiple sheets.",
                        max_length=255,
                        null=True,
                        verbose_name="Sheet Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("validating", "Validating"),
                            ("processing", "Processing"),
                            ("importing", "Importing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        help_text="Current import status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if import failed.",
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "observations_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of observations created.",
                        verbose_name="Observations Created",
                    ),
                ),
                (
                    "observations_updated",
                    models.IntegerField(
                        default=0,
                        help_text="Number of observations updated.",
                        verbose_name="Observations Updated",
                    ),
                ),
                (
                    "canonical_rates_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of canonical rates created (if canonicalized).",
                        verbose_name="Canonical Rates Created",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the import completed.",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this import.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fx_rate_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Market data source (e.g., BEAC).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fx_rate_imports",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "FX Rate Import",
                "verbose_name_plural": "FX Rate Imports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "status"],
                        name="reference_d_source__7b8329_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="reference_d_created_b663dc_idx"
                    ),
                ],
            },
        ),
    ]
