# Generated by Django 5.2 on 2025-12-31 01:39

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0004_alter_fxrateobservation_rate_type_fxrateimport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fxrate",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("mid", "Mid"),
                    ("official", "Official"),
                    ("fixing", "Fixing"),
                ],
                default="mid",
                help_text="Type of FX rate (BUY, SELL, MID, OFFICIAL, FIXING)",
                max_length=20,
                verbose_name="Rate Type",
            ),
        ),
        migrations.AlterField(
            model_name="fxrate",
            name="selection_reason",
            field=models.CharField(
                choices=[
                    ("auto_policy", "Auto Policy"),
                    ("auto_policy_mid_from_beac", "Auto Policy MID from BEAC"),
                    ("manual_override", "Manual Override"),
                    ("only_available", "Only Available"),
                ],
                default="auto_policy",
                help_text="Why this rate was selected (AUTO_POLICY, MANUAL_OVERRIDE, etc.)",
                max_length=30,
                verbose_name="Selection Reason",
            ),
        ),
        migrations.AlterField(
            model_name="fxrateobservation",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("buy", "Buy"),
                    ("sell", "Sell"),
                    ("mid", "Mid"),
                    ("official", "Official"),
                    ("fixing", "Fixing"),
                ],
                default="mid",
                help_text="Type of FX rate (BUY, SELL, MID, OFFICIAL, FIXING)",
                max_length=20,
                verbose_name="Rate Type",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentprice",
            name="selection_reason",
            field=models.CharField(
                choices=[
                    ("auto_policy", "Auto Policy"),
                    ("auto_policy_mid_from_beac", "Auto Policy MID from BEAC"),
                    ("manual_override", "Manual Override"),
                    ("only_available", "Only Available"),
                ],
                default="auto_policy",
                help_text="Why this price was selected (AUTO_POLICY, MANUAL_OVERRIDE, etc.)",
                max_length=30,
                verbose_name="Selection Reason",
            ),
        ),
        migrations.AlterField(
            model_name="yieldcurvepoint",
            name="selection_reason",
            field=models.CharField(
                choices=[
                    ("auto_policy", "Auto Policy"),
                    ("auto_policy_mid_from_beac", "Auto Policy MID from BEAC"),
                    ("manual_override", "Manual Override"),
                    ("only_available", "Only Available"),
                ],
                default="auto_policy",
                help_text="Why this point was selected (AUTO_POLICY, MANUAL_OVERRIDE, etc.)",
                max_length=30,
                verbose_name="Selection Reason",
            ),
        ),
        migrations.CreateModel(
            name="MarketIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the index (e.g., 'BVMAC', 'SP500')",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the index (e.g., 'BVMAC Index', 'S&P 500')",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "currency",
                    djmoney.models.fields.CurrencyField(
                        default="XAF",
                        help_text="Currency code for this index",
                        max_length=3,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "base_date",
                    models.DateField(
                        blank=True,
                        help_text="Base date for the index (when it started or was rebased)",
                        null=True,
                        verbose_name="Base Date",
                    ),
                ),
                (
                    "base_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Base value for the index (e.g., 100.0, 1000.0)",
                        max_digits=20,
                        null=True,
                        verbose_name="Base Value",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Market Index",
                "verbose_name_plural": "Market Indices",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="reference_d_code_8fa474_idx"),
                    models.Index(
                        fields=["currency"], name="reference_d_currenc_2a991d_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="reference_d_is_acti_97dde4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketIndexValueObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for which this index value is valid",
                        verbose_name="Date",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Index level/value on this date",
                        max_digits=20,
                        verbose_name="Value",
                    ),
                ),
                (
                    "return_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Daily return as percentage (if provided by source)",
                        max_digits=10,
                        null=True,
                        verbose_name="Return %",
                    ),
                ),
                (
                    "revision",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Revision number (0 = initial, 1+ = corrections)",
                        verbose_name="Revision",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        help_text="When this observation was received/recorded",
                        verbose_name="Observed At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_observations",
                        to="reference_data.marketindex",
                        verbose_name="Index",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="index_value_observations",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Index Value Observation",
                "verbose_name_plural": "Market Index Value Observations",
                "ordering": ["-date", "index", "-observed_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketIndexValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for which this index value is valid",
                        verbose_name="Date",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Index level/value on this date (stored directly for performance)",
                        max_digits=20,
                        verbose_name="Value",
                    ),
                ),
                (
                    "return_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Daily return as percentage",
                        max_digits=10,
                        null=True,
                        verbose_name="Return %",
                    ),
                ),
                (
                    "selection_reason",
                    models.CharField(
                        choices=[
                            ("auto_policy", "Auto Policy"),
                            ("auto_policy_mid_from_beac", "Auto Policy MID from BEAC"),
                            ("manual_override", "Manual Override"),
                            ("only_available", "Only Available"),
                        ],
                        default="auto_policy",
                        help_text="Why this value was selected (AUTO_POLICY, MANUAL_OVERRIDE, etc.)",
                        max_length=30,
                        verbose_name="Selection Reason",
                    ),
                ),
                (
                    "selected_at",
                    models.DateTimeField(
                        help_text="When this value was selected/canonicalized",
                        verbose_name="Selected At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "chosen_source",
                    models.ForeignKey(
                        help_text="The source that was selected for this canonical value",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canonical_index_values",
                        to="reference_data.marketdatasource",
                        verbose_name="Chosen Source",
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_values",
                        to="reference_data.marketindex",
                        verbose_name="Index",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who manually selected this value (if manual override)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_index_values",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Selected By",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The observation that was selected (optional, for audit trail)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canonical_values",
                        to="reference_data.marketindexvalueobservation",
                        verbose_name="Observation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Index Value",
                "verbose_name_plural": "Market Index Values",
                "ordering": ["-date", "index"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentPriceImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded Excel file with instrument price data.",
                        upload_to="market_data/instrument_prices/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True,
                        help_text="Sheet name if file has multiple sheets.",
                        max_length=255,
                        null=True,
                        verbose_name="Sheet Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("validating", "Validating"),
                            ("processing", "Processing"),
                            ("importing", "Importing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        help_text="Current import status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if import failed.",
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "observations_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of observations created.",
                        verbose_name="Observations Created",
                    ),
                ),
                (
                    "observations_updated",
                    models.IntegerField(
                        default=0,
                        help_text="Number of observations updated.",
                        verbose_name="Observations Updated",
                    ),
                ),
                (
                    "canonical_prices_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of canonical prices created (if canonicalized).",
                        verbose_name="Canonical Prices Created",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the import completed.",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this import.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instrument_price_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Market data source (e.g., BVMAC).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument_price_imports",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument Price Import",
                "verbose_name_plural": "Instrument Price Imports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "status"],
                        name="reference_d_source__7a6f59_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="reference_d_created_c8a5b3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketIndexConstituent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "as_of_date",
                    models.DateField(
                        help_text="Date when this constituent/weight is effective (time-versioned)",
                        verbose_name="As Of Date",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Weight of this instrument in the index (as percentage, e.g., 5.5 for 5.5%)",
                        max_digits=10,
                        verbose_name="Weight",
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Number of shares/units if provided by source",
                        max_digits=20,
                        null=True,
                        verbose_name="Shares",
                    ),
                ),
                (
                    "float_shares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Float-adjusted shares if provided by source",
                        max_digits=20,
                        null=True,
                        verbose_name="Float Shares",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "index",
                    models.ForeignKey(
                        help_text="The market index this constituent belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constituents",
                        to="reference_data.marketindex",
                        verbose_name="Index",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        help_text="The instrument that is a constituent of the index",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_constituents",
                        to="reference_data.instrument",
                        verbose_name="Instrument",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source of this constituent data (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="index_constituents",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Index Constituent",
                "verbose_name_plural": "Market Index Constituents",
                "ordering": ["-as_of_date", "index", "-weight"],
                "indexes": [
                    models.Index(
                        fields=["index", "as_of_date"],
                        name="reference_d_index_i_4041fe_idx",
                    ),
                    models.Index(
                        fields=["instrument", "as_of_date"],
                        name="reference_d_instrum_8e7f26_idx",
                    ),
                    models.Index(
                        fields=["as_of_date"], name="reference_d_as_of_d_e8cc17_idx"
                    ),
                ],
                "unique_together": {("index", "instrument", "as_of_date")},
            },
        ),
        migrations.CreateModel(
            name="MarketIndexImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded Excel file with market index data.",
                        upload_to="market_data/index_values/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True,
                        help_text="Sheet name if file has multiple sheets.",
                        max_length=255,
                        null=True,
                        verbose_name="Sheet Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("validating", "Validating"),
                            ("processing", "Processing"),
                            ("importing", "Importing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        help_text="Current import status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if import failed.",
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "observations_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of observations created.",
                        verbose_name="Observations Created",
                    ),
                ),
                (
                    "observations_updated",
                    models.IntegerField(
                        default=0,
                        help_text="Number of observations updated.",
                        verbose_name="Observations Updated",
                    ),
                ),
                (
                    "canonical_values_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of canonical values created (if canonicalized).",
                        verbose_name="Canonical Values Created",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the import completed.",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this import.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_index_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        help_text="Market index being imported.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="reference_data.marketindex",
                        verbose_name="Index",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Market data source (e.g., BVMAC).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_index_imports",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Index Import",
                "verbose_name_plural": "Market Index Imports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["index", "status"],
                        name="reference_d_index_i_ed29bd_idx",
                    ),
                    models.Index(
                        fields=["source", "status"],
                        name="reference_d_source__4b33a9_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="reference_d_created_577ff5_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="marketindexvalueobservation",
            index=models.Index(
                fields=["index", "date"], name="reference_d_index_i_b4d7c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketindexvalueobservation",
            index=models.Index(fields=["date"], name="reference_d_date_aa07ea_idx"),
        ),
        migrations.AddIndex(
            model_name="marketindexvalueobservation",
            index=models.Index(
                fields=["source", "date"], name="reference_d_source__ecfb16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketindexvalueobservation",
            index=models.Index(
                fields=["observed_at"], name="reference_d_observe_ae3a5d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketindexvalueobservation",
            unique_together={("index", "date", "source", "revision")},
        ),
        migrations.AddIndex(
            model_name="marketindexvalue",
            index=models.Index(
                fields=["index", "date"], name="reference_d_index_i_0d3367_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketindexvalue",
            index=models.Index(fields=["date"], name="reference_d_date_ec23a6_idx"),
        ),
        migrations.AddIndex(
            model_name="marketindexvalue",
            index=models.Index(
                fields=["chosen_source"], name="reference_d_chosen__3f46e3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketindexvalue",
            unique_together={("index", "date")},
        ),
    ]
