# Generated by Django 5.2 on 2025-12-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        (
            "reference_data",
            "0005_alter_fxrate_rate_type_alter_fxrate_selection_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="amortization_method",
            field=models.CharField(
                blank=True,
                help_text="Amortization method (e.g., 'BULLET', 'AMORTIZING', 'ZERO_COUPON').",
                max_length=50,
                null=True,
                verbose_name="Amortization Method",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="coupon_frequency",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Coupon Frequency"
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="face_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Face value or par value of the bond.",
                max_digits=20,
                null=True,
                verbose_name="Face Value",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="first_listing_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the bond was first listed on an exchange.",
                null=True,
                verbose_name="First Listing Date",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="fund_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diversified", "Diversified"),
                    ("money_market", "Money Market"),
                    ("bond", "Bond"),
                    ("equity", "Equity"),
                ],
                help_text="Fund category indicating asset type composition (DIVERSIFIED, MONEY_MARKET, BOND, EQUITY).",
                max_length=20,
                null=True,
                verbose_name="Fund Category",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="fund_launch_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the fund was launched.",
                null=True,
                verbose_name="Fund Launch Date",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="last_coupon_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the last coupon payment.",
                null=True,
                verbose_name="Last Coupon Date",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="next_coupon_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the next scheduled coupon payment.",
                null=True,
                verbose_name="Next Coupon Date",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="original_offering_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original offering amount at issuance.",
                max_digits=20,
                null=True,
                verbose_name="Original Offering Amount",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="units_outstanding",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Number of units/shares currently outstanding.",
                max_digits=20,
                null=True,
                verbose_name="Units Outstanding",
            ),
        ),
        migrations.AlterField(
            model_name="fxrateimport",
            name="sheet_name",
            field=models.CharField(
                blank=True,
                default="FX_RATES",
                help_text="Sheet name if file has multiple sheets. Defaults to 'FX_RATES'.",
                max_length=255,
                null=True,
                verbose_name="Sheet Name",
            ),
        ),
        migrations.AlterField(
            model_name="marketindeximport",
            name="sheet_name",
            field=models.CharField(
                blank=True,
                default="INDEX_LEVELS",
                help_text="Sheet name if file has multiple sheets. Defaults to 'INDEX_LEVELS'.",
                max_length=255,
                null=True,
                verbose_name="Sheet Name",
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "maturity_date"],
                name="reference_d_organiz_d6bf1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "first_listing_date"],
                name="reference_d_organiz_cc72c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "next_coupon_date"],
                name="reference_d_organiz_548689_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["organization", "fund_category"],
                name="reference_d_organiz_bca7ff_idx",
            ),
        ),
    ]
