# Generated by Django 5.2 on 2026-01-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0007_add_issuer_code_lei"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="issuer",
            new_name="reference_d_issuer__2587fb_idx",
            old_name="reference_d_issuer__code_idx",
        ),
    ]
