# Generated by Django 5.2 on 2026-01-02 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("reference_data", "0008_add_issuer_code_lei"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketDataSourcePriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("fx_rate", "FX Rate"),
                            ("price", "Price"),
                            ("yield_curve", "Yield Curve"),
                            ("index_value", "Index Value"),
                        ],
                        help_text="Type of market data this priority applies to.",
                        max_length=20,
                        verbose_name="Data Type",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        help_text="Priority rank for this org/data_type combination (lower = higher priority).",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Market data source this priority applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_priority_overrides",
                        to="reference_data.marketdatasource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Data Source Priority Override",
                "verbose_name_plural": "Market Data Source Priority Overrides",
                "indexes": [
                    models.Index(
                        fields=["organization", "data_type", "priority"],
                        name="reference_d_organiz_eac3ea_idx",
                    ),
                    models.Index(
                        fields=["organization", "data_type", "source"],
                        name="reference_d_organiz_b6fd2a_idx",
                    ),
                ],
                "unique_together": {("organization", "data_type", "source")},
            },
        ),
    ]
