# Generated by Django 5.2 on 2026-01-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("reference_data", "0009_marketdatasourcepriority"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Short code identifier (e.g., 'BANK', 'SOV').",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Issuer Group",
                "verbose_name_plural": "Issuer Groups",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="issuer",
            new_name="reference_d_organiz_f8f4a6_idx",
            old_name="reference_d_organiz_a7c80a_idx",
        ),
        migrations.AlterField(
            model_name="issuer",
            name="issuer_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stable identifier code for cross-org consistency (globally unique).",
                max_length=50,
                null=True,
                verbose_name="Issuer Code",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("isin__isnull", True), _negated=True),
                    models.Q(("isin", ""), _negated=True),
                ),
                fields=("organization", "isin"),
                name="unique_instrument_isin_per_org_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("ticker__isnull", True), _negated=True),
                    models.Q(("ticker", ""), _negated=True),
                ),
                fields=("organization", "ticker"),
                name="unique_instrument_ticker_per_org_not_null",
            ),
        ),
        migrations.AddField(
            model_name="issuergroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent group for hierarchical structure.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="reference_data.issuergroup",
                verbose_name="Parent Group",
            ),
        ),
        migrations.AlterField(
            model_name="issuer",
            name="issuer_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group classification for this issuer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issuers",
                to="reference_data.issuergroup",
                verbose_name="Issuer Group",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuer",
            constraint=models.UniqueConstraint(
                fields=("organization", "issuer_code"), name="unique_issuer_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="issuergroup",
            index=models.Index(fields=["code"], name="reference_d_code_56eb41_idx"),
        ),
        migrations.AddIndex(
            model_name="issuergroup",
            index=models.Index(
                fields=["parent", "is_active"], name="reference_d_parent__0c1221_idx"
            ),
        ),
    ]
