# Generated by Django 5.2 on 2026-01-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0010_issuergroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuer",
            name="lei",
            field=models.CharField(
                blank=True,
                help_text="Legal Entity Identifier (20-character code).",
                max_length=20,
                null=True,
                verbose_name="LEI",
            ),
        ),
    ]
