# Generated by Django 5.2 on 2026-01-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0012_update_issuer_code_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="yieldcurve",
            name="last_observation_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the most recent observation for this curve",
                null=True,
                verbose_name="Last Observation Date",
            ),
        ),
    ]
