# Generated by Django 5.2 on 2026-01-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0013_yieldcurve_last_observation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="yieldcurvepoint",
            name="published_date_assumed",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether last_published_date was assumed to equal curve_date (date) "
                    "because publication date was not provided by the source."
                ),
                verbose_name="Published Date Assumed",
            ),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepoint",
            index=models.Index(
                fields=["published_date_assumed"], name="reference_published_idx"
            ),
        ),
    ]
