# Generated by Django 5.2 on 2026-01-02 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0014_yieldcurvepoint_published_date_assumed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="yieldcurvepoint",
            new_name="reference_d_publish_d477f4_idx",
            old_name="reference_published_idx",
        ),
        migrations.AddField(
            model_name="yieldcurvepoint",
            name="is_official",
            field=models.BooleanField(
                default=True,
                help_text="Whether this is official data (e.g., from BEAC central bank)",
                verbose_name="Is Official",
            ),
        ),
        migrations.AddField(
            model_name="yieldcurvepoint",
            name="last_published_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the source published this data (for staleness tracking). If not provided, defaults to curve_date (date) and published_date_assumed is set to True.",
                null=True,
                verbose_name="Last Published Date",
            ),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepoint",
            index=models.Index(
                fields=["last_published_date"], name="reference_d_last_pu_dafcdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yieldcurvepoint",
            index=models.Index(
                fields=["is_official", "last_published_date"],
                name="reference_d_is_offi_96186f_idx",
            ),
        ),
        migrations.AlterField(
            model_name="yieldcurvepointobservation",
            name="observed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this observation was received/recorded (optional)",
                null=True,
                verbose_name="Observed At",
            ),
        ),
    ]
