# Generated by Django 5.2 on 2026-01-02 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference_data",
            "0015_rename_reference_published_idx_reference_d_publish_d477f4_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="YieldCurveStressProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "narrative",
                    models.CharField(
                        help_text="Stress narrative type (e.g., 'gradual_deterioration', 'acute_sovereign_stress').",
                        max_length=50,
                        verbose_name="Narrative",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="Start date of historical period this profile is based on.",
                        verbose_name="Period Start",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="End date of historical period.",
                        verbose_name="Period End",
                    ),
                ),
                (
                    "regime_type",
                    models.CharField(
                        help_text="Regime classification (normal, rising_stress, high_stress, etc.).",
                        max_length=30,
                        verbose_name="Regime Type",
                    ),
                ),
                (
                    "sovereign_haircut_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Haircut percentage for sovereign issuers (0-100).",
                        max_digits=5,
                        verbose_name="Sovereign Haircut %",
                    ),
                ),
                (
                    "corporate_haircut_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Haircut percentage for corporate issuers (0-100).",
                        max_digits=5,
                        verbose_name="Corporate Haircut %",
                    ),
                ),
                (
                    "supra_haircut_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Haircut percentage for supranational issuers (0-100).",
                        max_digits=5,
                        verbose_name="Supranational Haircut %",
                    ),
                ),
                (
                    "calibration_rationale",
                    models.TextField(
                        help_text="Explanation of how haircuts were calibrated from historical narrative.",
                        verbose_name="Calibration Rationale",
                    ),
                ),
                (
                    "last_observation_date",
                    models.DateField(
                        blank=True,
                        help_text="Last observation date from YieldCurve (for staleness tracking).",
                        null=True,
                        verbose_name="Last Observation Date",
                    ),
                ),
                (
                    "staleness_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Computed staleness in days (from last_observation_date).",
                        null=True,
                        verbose_name="Staleness Days",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this profile is currently active for stress testing.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "curve",
                    models.ForeignKey(
                        help_text="Yield curve this stress profile applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stress_profiles",
                        to="reference_data.yieldcurve",
                        verbose_name="Curve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yield Curve Stress Profile",
                "verbose_name_plural": "Yield Curve Stress Profiles",
                "ordering": ["-period_end", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["curve", "is_active"],
                        name="reference_d_curve_i_98e3aa_idx",
                    ),
                    models.Index(
                        fields=["narrative", "is_active"],
                        name="reference_d_narrati_e51d46_idx",
                    ),
                    models.Index(
                        fields=["regime_type"], name="reference_d_regime__025878_idx"
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="reference_d_period__030fbb_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sovereign_haircut_pct__gte", 0),
                            ("sovereign_haircut_pct__lte", 100),
                        ),
                        name="valid_sovereign_haircut",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("corporate_haircut_pct__gte", 0),
                            ("corporate_haircut_pct__lte", 100),
                        ),
                        name="valid_corporate_haircut",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("supra_haircut_pct__gte", 0),
                            ("supra_haircut_pct__lte", 100),
                        ),
                        name="valid_supra_haircut",
                    ),
                ],
            },
        ),
    ]
