# Generated by Django 5.2 on 2025-12-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="portfolio",
            name="portfolios__organiz_f59e71_idx",
        ),
        migrations.RemoveIndex(
            model_name="portfoliogroup",
            name="portfolios__organiz_abfabc_idx",
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="portfoliogroup",
            unique_together={("organization", "name")},
        ),
        migrations.AddField(
            model_name="portfolio",
            name="full_name",
            field=models.TextField(
                blank=True,
                help_text="Full name of the portfolio.",
                null=True,
                verbose_name="Full Name",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(
                help_text="Short name of the portfolio.",
                max_length=10,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliogroup",
            name="name",
            field=models.CharField(
                help_text="Short name of the group.", max_length=10, verbose_name="Name"
            ),
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="code",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="description",
        ),
        migrations.RemoveField(
            model_name="portfoliogroup",
            name="code",
        ),
    ]
