# Generated by Django 5.2 on 2025-12-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0003_alter_positionsnapshot_accrued_interest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("parsing", "Parsing"),
                    ("validating", "Validating"),
                    ("processing", "Processing"),
                    ("importing", "Importing"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                default="pending",
                help_text="Current import status.",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
