# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0004_alter_portfolioimport_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioImportError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(
                        help_text="Row number in source file (1-indexed, includes header).",
                        verbose_name="Row Number",
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        blank=True,
                        help_text="Column where error occurred (if applicable).",
                        max_length=255,
                        null=True,
                        verbose_name="Column Name",
                    ),
                ),
                (
                    "raw_row_data",
                    models.JSONField(
                        help_text="Original row data as dict for debugging.",
                        verbose_name="Raw Row Data",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("validation", "Validation Error"),
                            ("mapping", "Mapping Error"),
                            ("reference_data", "Reference Data Missing"),
                            ("format", "Format Error"),
                            ("business_rule", "Business Rule Violation"),
                            ("system", "System Error"),
                        ],
                        help_text="Type of error.",
                        max_length=50,
                        verbose_name="Error Type",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        help_text="Human-readable error message.",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Machine-readable error code.",
                        max_length=50,
                        null=True,
                        verbose_name="Error Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "portfolio_import",
                    models.ForeignKey(
                        help_text="Import this error belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="portfolios.portfolioimport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Import Error",
                "verbose_name_plural": "Portfolio Import Errors",
                "ordering": ["portfolio_import", "row_number"],
            },
        ),
        migrations.AddIndex(
            model_name="portfolioimporterror",
            index=models.Index(
                fields=["organization", "portfolio_import", "row_number"],
                name="portfolios_p_organiz_abc123_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioimporterror",
            index=models.Index(
                fields=["organization", "portfolio_import", "error_type"],
                name="portfolios_p_organiz_def456_idx",
            ),
        ),
    ]
