# Generated by Django 5.2 on 2025-12-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0005_add_portfolio_import_error"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="portfolioimporterror",
            new_name="portfolios__organiz_deffea_idx",
            old_name="portfolios_p_organiz_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="portfolioimporterror",
            new_name="portfolios__organiz_a833b9_idx",
            old_name="portfolios_p_organiz_def456_idx",
        ),
        migrations.AlterField(
            model_name="positionsnapshot",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Price per unit used for valuation.",
                max_digits=20,
                null=True,
                verbose_name="Price",
            ),
        ),
    ]
