"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")


# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


THIRD_PARTY_APPS = [
    "storages",
    "django_celery_beat",
    "django_celery_results",
    "django_countries",  # Note: package name is django-countries, but module is django_countries
    "djmoney",
]

LOCAL_APPS = [
    "apps.organizations",
    "apps.accounts",
    "apps.reference_data",
    "apps.portfolios",
    "apps.analytics",
    "apps.reports",
    "apps.etl",
    "apps.audit",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Must be after SessionMiddleware, before CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Multi-tenant org context (safe default: does nothing if user anonymous)
    "apps.organizations.middleware.OrganizationContextMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "apps" / "reports" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "hedgeminddb_dev"),
        "USER": os.environ.get("POSTGRES_USER", "hedgemind_user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "risk_platform"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", "English"),
    ("fr", "French"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "Africa/Douala")

USE_I18N = True
USE_L10N = True  # Enable localization (number/date formatting)
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default currency settings for djmoney
DEFAULT_CURRENCY = "XAF"  # Central African CFA franc ("XAF" is ISO code; if using a custom/non-ISO code use with care)

# If you want S3/R2 storage: set USE_S3=1 and vars below
USE_S3 = os.environ.get("USE_S3", "0") == "1"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------
# Celery configuration
# --------------------
# Celery configuration settings:
# - CELERY_BROKER_URL: Connection URL for the Celery broker (such as Redis or RabbitMQ), determines where Celery sends and receives task messages.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")

# - CELERY_TIMEZONE: Time zone Celery should use for scheduling tasks.
CELERY_TIMEZONE = TIME_ZONE

# - CELERY_ACCEPT_CONTENT: List of content-types the worker will accept for tasks.
CELERY_ACCEPT_CONTENT = os.environ.get("CELERY_ACCEPT_CONTENT", "json").split(",")

# - CELERY_TASK_SERIALIZER: Format used to serialize task arguments.
CELERY_TASK_SERIALIZER = os.environ.get("CELERY_TASK_SERIALIZER", "json")

# - CELERY_RESULT_SERIALIZER: Format used to serialize results.
CELERY_RESULT_SERIALIZER = os.environ.get("CELERY_RESULT_SERIALIZER", "json")

# - CELERY_TASK_TRACK_STARTED: If True, tasks include a 'started' state before completing.
CELERY_TASK_TRACK_STARTED = (
    os.environ.get("CELERY_TASK_TRACK_STARTED", "True") == "True"
)

# - CELERY_RESULT_BACKEND: Backend used to store task results.
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "django-db")

# - CELERY_CACHE_BACKEND: Backend to use for caching in Celery (if required).
CELERY_CACHE_BACKEND = os.environ.get("CELERY_CACHE_BACKEND", "django-cache")

# - CELERY_TASK_ACKS_LATE: If True, tasks are acknowledged after being completed, helping with task reliability.
CELERY_TASK_ACKS_LATE = os.environ.get("CELERY_TASK_ACKS_LATE", "True") == "True"

# - CELERY_WORKER_PREFETCH_MULTIPLIER: Number of tasks a worker will prefetch, as a multiplier of concurrency.
CELERY_WORKER_PREFETCH_MULTIPLIER = os.environ.get(
    "CELERY_WORKER_PREFETCH_MULTIPLIER", "4"
)
