# Generated by Django 5.2 on 2025-12-30 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Organization context for this action (optional for system-wide actions).",
                        null=True,
                        verbose_name="Organization ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Type of action performed (e.g., 'CREATE', 'UPDATE', 'DELETE', 'LOAD_REFERENCE_DATA').",
                        max_length=100,
                        verbose_name="Action",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of object affected (e.g., 'InstrumentGroup', 'InstrumentType').",
                        max_length=100,
                        verbose_name="Object Type",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the affected object (optional).",
                        null=True,
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the affected object.",
                        max_length=255,
                        null=True,
                        verbose_name="Object Representation",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context as JSON (e.g., details about the operation).",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this audit event occurred.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action (None for system/automated actions).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization_id", "created_at"],
                        name="audit_audit_organiz_4fc53a_idx",
                    ),
                    models.Index(
                        fields=["action", "object_type"],
                        name="audit_audit_action_5a1abc_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_audit_actor_i_58da28_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_audit_object__0e78a5_idx",
                    ),
                ],
            },
        ),
    ]
