# Generated by Django 5.2 on 2025-12-31 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        (
            "portfolios",
            "0006_rename_portfolios_p_organiz_abc123_idx_portfolios__organiz_deffea_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValuationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "as_of_date",
                    models.DateField(
                        help_text="As-of date for this valuation run.",
                        verbose_name="As Of Date",
                    ),
                ),
                (
                    "valuation_policy",
                    models.CharField(
                        choices=[
                            ("use_snapshot_mv", "Use Snapshot Market Value"),
                            ("revalue_from_marketdata", "Revalue from Market Data"),
                        ],
                        default="use_snapshot_mv",
                        help_text="Policy used for valuation.",
                        max_length=30,
                        verbose_name="Valuation Policy",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the official valuation for this portfolio/date.",
                        verbose_name="Is Official",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current run status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "inputs_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hash of position snapshots + market data for idempotency checks.",
                        max_length=64,
                        null=True,
                        verbose_name="Inputs Hash",
                    ),
                ),
                (
                    "log",
                    models.TextField(
                        blank=True,
                        help_text="Execution log for debugging.",
                        null=True,
                        verbose_name="Log",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this valuation run.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valuation_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        help_text="Portfolio being valued.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_runs",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valuation Run",
                "verbose_name_plural": "Valuation Runs",
                "ordering": ["-as_of_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "portfolio", "as_of_date"],
                        name="analytics_v_organiz_be0885_idx",
                    ),
                    models.Index(
                        fields=[
                            "organization",
                            "portfolio",
                            "as_of_date",
                            "is_official",
                        ],
                        name="analytics_v_organiz_cdcb73_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="analytics_v_organiz_ee3eca_idx",
                    ),
                    models.Index(
                        fields=["organization", "created_at"],
                        name="analytics_v_organiz_e7ff4e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("inputs_hash__isnull", False)),
                        fields=(
                            "organization",
                            "portfolio",
                            "as_of_date",
                            "inputs_hash",
                        ),
                        name="uniq_valuation_run_org_port_date_inputs",
                    )
                ],
            },
        ),
    ]
