# Generated by Django 5.2 on 2026-01-01 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_valuationpositionresult"),
        ("organizations", "0001_initial"),
        (
            "portfolios",
            "0006_rename_portfolios_p_organiz_abc123_idx_portfolios__organiz_deffea_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="valuationrun",
            name="run_context_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifier for execution context and configuration. Groups runs executed with the same settings (single or batch). Used for audit trail and reproducibility.",
                max_length=64,
                null=True,
                verbose_name="Run Context ID",
            ),
        ),
        migrations.AddIndex(
            model_name="valuationrun",
            index=models.Index(
                fields=["organization", "run_context_id"],
                name="analytics_v_organiz_75b22d_idx",
            ),
        ),
    ]
