# Generated by Django 5.2 on 2026-01-02 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0005_exposureresult"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Portfolio Overview v1').",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version identifier (e.g., '1.0', 'v1').",
                        max_length=50,
                        verbose_name="Version",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        help_text="Type of template (e.g., 'portfolio_overview').",
                        max_length=50,
                        verbose_name="Template Type",
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Template configuration (sections, layouts, etc.).",
                        verbose_name="Configuration JSON",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is currently active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ["name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current generation status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF file.",
                        null=True,
                        upload_to="reports/%Y/%m/%d/",
                        verbose_name="PDF File",
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated CSV file.",
                        null=True,
                        upload_to="reports/%Y/%m/%d/",
                        verbose_name="CSV File",
                    ),
                ),
                (
                    "excel_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated Excel file.",
                        null=True,
                        upload_to="reports/%Y/%m/%d/",
                        verbose_name="Excel File",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the report was generated.",
                        null=True,
                        verbose_name="Generated At",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed.",
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "valuation_run",
                    models.ForeignKey(
                        help_text="Valuation run this report is based on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="analytics.valuationrun",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template used to generate this report.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["organization", "template_type", "is_active"],
                name="reports_rep_organiz_ad2b90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["organization", "name", "version"],
                name="reports_rep_organiz_c62694_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "name", "version"),
                name="uniq_report_template_org_name_version",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["organization", "valuation_run"],
                name="reports_rep_organiz_550560_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["organization", "status"], name="reports_rep_organiz_ae5072_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["organization", "template"],
                name="reports_rep_organiz_26d484_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["organization", "created_at"],
                name="reports_rep_organiz_b5f8b2_idx",
            ),
        ),
    ]
